/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPosRouteImport } from './routes/_app.pos'
import { Route as AppStoreTransfersRouteImport } from './routes/_app.store.transfers'
import { Route as AppStoreStoresRouteImport } from './routes/_app.store.stores'
import { Route as AppStoreStockRouteImport } from './routes/_app.store.stock'
import { Route as AppStakeholdersSuppliersRouteImport } from './routes/_app.stakeholders.suppliers'
import { Route as AppStakeholdersCustomersRouteImport } from './routes/_app.stakeholders.customers'
import { Route as AppSalesReportsRouteImport } from './routes/_app.sales.reports'
import { Route as AppSalesReceiptsRouteImport } from './routes/_app.sales.receipts'
import { Route as AppSalesInvoicesRouteImport } from './routes/_app.sales.invoices'
import { Route as AppSalesInterBranchRouteImport } from './routes/_app.sales.inter-branch'
import { Route as AppSalesCustomerStatementRouteImport } from './routes/_app.sales.customer-statement'
import { Route as AppProductsSelfServiceRouteImport } from './routes/_app.products.self-service'
import { Route as AppProductsPurchaseOrdersRouteImport } from './routes/_app.products.purchase-orders'
import { Route as AppProductsExpensesRouteImport } from './routes/_app.products.expenses'
import { Route as AppProductsCatalogRouteImport } from './routes/_app.products.catalog'
import { Route as AppHrStaffRouteImport } from './routes/_app.hr.staff'
import { Route as AppHrSalaryRouteImport } from './routes/_app.hr.salary'
import { Route as AppHrPayrollRouteImport } from './routes/_app.hr.payroll'
import { Route as AppHrLeaveRouteImport } from './routes/_app.hr.leave'
import { Route as AppFinanceReportsRouteImport } from './routes/_app.finance.reports'
import { Route as AppFinanceReconciliationRouteImport } from './routes/_app.finance.reconciliation'
import { Route as AppFinancePaymentVouchersRouteImport } from './routes/_app.finance.payment-vouchers'
import { Route as AppFinanceLedgersRouteImport } from './routes/_app.finance.ledgers'
import { Route as AppFinanceChartOfAccountsRouteImport } from './routes/_app.finance.chart-of-accounts'
import { Route as AppFinanceBankCashRouteImport } from './routes/_app.finance.bank-cash'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminSettingsRouteImport } from './routes/_app.admin.settings'
import { Route as AppSalesInvoicesIndexRouteImport } from './routes/_app.sales.invoices.index'
import { Route as AppSalesInvoicesProformaRouteImport } from './routes/_app.sales.invoices.proforma'
import { Route as AppSalesInvoicesNewRouteImport } from './routes/_app.sales.invoices.new'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreTransfersRoute = AppStoreTransfersRouteImport.update({
  id: '/store/transfers',
  path: '/store/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreStoresRoute = AppStoreStoresRouteImport.update({
  id: '/store/stores',
  path: '/store/stores',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreStockRoute = AppStoreStockRouteImport.update({
  id: '/store/stock',
  path: '/store/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppStakeholdersSuppliersRoute =
  AppStakeholdersSuppliersRouteImport.update({
    id: '/stakeholders/suppliers',
    path: '/stakeholders/suppliers',
    getParentRoute: () => AppRoute,
  } as any)
const AppStakeholdersCustomersRoute =
  AppStakeholdersCustomersRouteImport.update({
    id: '/stakeholders/customers',
    path: '/stakeholders/customers',
    getParentRoute: () => AppRoute,
  } as any)
const AppSalesReportsRoute = AppSalesReportsRouteImport.update({
  id: '/sales/reports',
  path: '/sales/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesReceiptsRoute = AppSalesReceiptsRouteImport.update({
  id: '/sales/receipts',
  path: '/sales/receipts',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesInvoicesRoute = AppSalesInvoicesRouteImport.update({
  id: '/sales/invoices',
  path: '/sales/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesInterBranchRoute = AppSalesInterBranchRouteImport.update({
  id: '/sales/inter-branch',
  path: '/sales/inter-branch',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesCustomerStatementRoute =
  AppSalesCustomerStatementRouteImport.update({
    id: '/sales/customer-statement',
    path: '/sales/customer-statement',
    getParentRoute: () => AppRoute,
  } as any)
const AppProductsSelfServiceRoute = AppProductsSelfServiceRouteImport.update({
  id: '/products/self-service',
  path: '/products/self-service',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsPurchaseOrdersRoute =
  AppProductsPurchaseOrdersRouteImport.update({
    id: '/products/purchase-orders',
    path: '/products/purchase-orders',
    getParentRoute: () => AppRoute,
  } as any)
const AppProductsExpensesRoute = AppProductsExpensesRouteImport.update({
  id: '/products/expenses',
  path: '/products/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsCatalogRoute = AppProductsCatalogRouteImport.update({
  id: '/products/catalog',
  path: '/products/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppHrStaffRoute = AppHrStaffRouteImport.update({
  id: '/hr/staff',
  path: '/hr/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppHrSalaryRoute = AppHrSalaryRouteImport.update({
  id: '/hr/salary',
  path: '/hr/salary',
  getParentRoute: () => AppRoute,
} as any)
const AppHrPayrollRoute = AppHrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppHrLeaveRoute = AppHrLeaveRouteImport.update({
  id: '/hr/leave',
  path: '/hr/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceReportsRoute = AppFinanceReportsRouteImport.update({
  id: '/finance/reports',
  path: '/finance/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceReconciliationRoute =
  AppFinanceReconciliationRouteImport.update({
    id: '/finance/reconciliation',
    path: '/finance/reconciliation',
    getParentRoute: () => AppRoute,
  } as any)
const AppFinancePaymentVouchersRoute =
  AppFinancePaymentVouchersRouteImport.update({
    id: '/finance/payment-vouchers',
    path: '/finance/payment-vouchers',
    getParentRoute: () => AppRoute,
  } as any)
const AppFinanceLedgersRoute = AppFinanceLedgersRouteImport.update({
  id: '/finance/ledgers',
  path: '/finance/ledgers',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceChartOfAccountsRoute =
  AppFinanceChartOfAccountsRouteImport.update({
    id: '/finance/chart-of-accounts',
    path: '/finance/chart-of-accounts',
    getParentRoute: () => AppRoute,
  } as any)
const AppFinanceBankCashRoute = AppFinanceBankCashRouteImport.update({
  id: '/finance/bank-cash',
  path: '/finance/bank-cash',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesInvoicesIndexRoute = AppSalesInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesInvoicesRoute,
} as any)
const AppSalesInvoicesProformaRoute =
  AppSalesInvoicesProformaRouteImport.update({
    id: '/proforma',
    path: '/proforma',
    getParentRoute: () => AppSalesInvoicesRoute,
  } as any)
const AppSalesInvoicesNewRoute = AppSalesInvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSalesInvoicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/pos': typeof AppPosRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/finance/bank-cash': typeof AppFinanceBankCashRoute
  '/finance/chart-of-accounts': typeof AppFinanceChartOfAccountsRoute
  '/finance/ledgers': typeof AppFinanceLedgersRoute
  '/finance/payment-vouchers': typeof AppFinancePaymentVouchersRoute
  '/finance/reconciliation': typeof AppFinanceReconciliationRoute
  '/finance/reports': typeof AppFinanceReportsRoute
  '/hr/leave': typeof AppHrLeaveRoute
  '/hr/payroll': typeof AppHrPayrollRoute
  '/hr/salary': typeof AppHrSalaryRoute
  '/hr/staff': typeof AppHrStaffRoute
  '/products/catalog': typeof AppProductsCatalogRoute
  '/products/expenses': typeof AppProductsExpensesRoute
  '/products/purchase-orders': typeof AppProductsPurchaseOrdersRoute
  '/products/self-service': typeof AppProductsSelfServiceRoute
  '/sales/customer-statement': typeof AppSalesCustomerStatementRoute
  '/sales/inter-branch': typeof AppSalesInterBranchRoute
  '/sales/invoices': typeof AppSalesInvoicesRouteWithChildren
  '/sales/receipts': typeof AppSalesReceiptsRoute
  '/sales/reports': typeof AppSalesReportsRoute
  '/stakeholders/customers': typeof AppStakeholdersCustomersRoute
  '/stakeholders/suppliers': typeof AppStakeholdersSuppliersRoute
  '/store/stock': typeof AppStoreStockRoute
  '/store/stores': typeof AppStoreStoresRoute
  '/store/transfers': typeof AppStoreTransfersRoute
  '/sales/invoices/new': typeof AppSalesInvoicesNewRoute
  '/sales/invoices/proforma': typeof AppSalesInvoicesProformaRoute
  '/sales/invoices/': typeof AppSalesInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/pos': typeof AppPosRoute
  '/': typeof AppIndexRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/finance/bank-cash': typeof AppFinanceBankCashRoute
  '/finance/chart-of-accounts': typeof AppFinanceChartOfAccountsRoute
  '/finance/ledgers': typeof AppFinanceLedgersRoute
  '/finance/payment-vouchers': typeof AppFinancePaymentVouchersRoute
  '/finance/reconciliation': typeof AppFinanceReconciliationRoute
  '/finance/reports': typeof AppFinanceReportsRoute
  '/hr/leave': typeof AppHrLeaveRoute
  '/hr/payroll': typeof AppHrPayrollRoute
  '/hr/salary': typeof AppHrSalaryRoute
  '/hr/staff': typeof AppHrStaffRoute
  '/products/catalog': typeof AppProductsCatalogRoute
  '/products/expenses': typeof AppProductsExpensesRoute
  '/products/purchase-orders': typeof AppProductsPurchaseOrdersRoute
  '/products/self-service': typeof AppProductsSelfServiceRoute
  '/sales/customer-statement': typeof AppSalesCustomerStatementRoute
  '/sales/inter-branch': typeof AppSalesInterBranchRoute
  '/sales/receipts': typeof AppSalesReceiptsRoute
  '/sales/reports': typeof AppSalesReportsRoute
  '/stakeholders/customers': typeof AppStakeholdersCustomersRoute
  '/stakeholders/suppliers': typeof AppStakeholdersSuppliersRoute
  '/store/stock': typeof AppStoreStockRoute
  '/store/stores': typeof AppStoreStoresRoute
  '/store/transfers': typeof AppStoreTransfersRoute
  '/sales/invoices/new': typeof AppSalesInvoicesNewRoute
  '/sales/invoices/proforma': typeof AppSalesInvoicesProformaRoute
  '/sales/invoices': typeof AppSalesInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/pos': typeof AppPosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/finance/bank-cash': typeof AppFinanceBankCashRoute
  '/_app/finance/chart-of-accounts': typeof AppFinanceChartOfAccountsRoute
  '/_app/finance/ledgers': typeof AppFinanceLedgersRoute
  '/_app/finance/payment-vouchers': typeof AppFinancePaymentVouchersRoute
  '/_app/finance/reconciliation': typeof AppFinanceReconciliationRoute
  '/_app/finance/reports': typeof AppFinanceReportsRoute
  '/_app/hr/leave': typeof AppHrLeaveRoute
  '/_app/hr/payroll': typeof AppHrPayrollRoute
  '/_app/hr/salary': typeof AppHrSalaryRoute
  '/_app/hr/staff': typeof AppHrStaffRoute
  '/_app/products/catalog': typeof AppProductsCatalogRoute
  '/_app/products/expenses': typeof AppProductsExpensesRoute
  '/_app/products/purchase-orders': typeof AppProductsPurchaseOrdersRoute
  '/_app/products/self-service': typeof AppProductsSelfServiceRoute
  '/_app/sales/customer-statement': typeof AppSalesCustomerStatementRoute
  '/_app/sales/inter-branch': typeof AppSalesInterBranchRoute
  '/_app/sales/invoices': typeof AppSalesInvoicesRouteWithChildren
  '/_app/sales/receipts': typeof AppSalesReceiptsRoute
  '/_app/sales/reports': typeof AppSalesReportsRoute
  '/_app/stakeholders/customers': typeof AppStakeholdersCustomersRoute
  '/_app/stakeholders/suppliers': typeof AppStakeholdersSuppliersRoute
  '/_app/store/stock': typeof AppStoreStockRoute
  '/_app/store/stores': typeof AppStoreStoresRoute
  '/_app/store/transfers': typeof AppStoreTransfersRoute
  '/_app/sales/invoices/new': typeof AppSalesInvoicesNewRoute
  '/_app/sales/invoices/proforma': typeof AppSalesInvoicesProformaRoute
  '/_app/sales/invoices/': typeof AppSalesInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pos'
    | '/admin/settings'
    | '/admin/users'
    | '/finance/bank-cash'
    | '/finance/chart-of-accounts'
    | '/finance/ledgers'
    | '/finance/payment-vouchers'
    | '/finance/reconciliation'
    | '/finance/reports'
    | '/hr/leave'
    | '/hr/payroll'
    | '/hr/salary'
    | '/hr/staff'
    | '/products/catalog'
    | '/products/expenses'
    | '/products/purchase-orders'
    | '/products/self-service'
    | '/sales/customer-statement'
    | '/sales/inter-branch'
    | '/sales/invoices'
    | '/sales/receipts'
    | '/sales/reports'
    | '/stakeholders/customers'
    | '/stakeholders/suppliers'
    | '/store/stock'
    | '/store/stores'
    | '/store/transfers'
    | '/sales/invoices/new'
    | '/sales/invoices/proforma'
    | '/sales/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pos'
    | '/'
    | '/admin/settings'
    | '/admin/users'
    | '/finance/bank-cash'
    | '/finance/chart-of-accounts'
    | '/finance/ledgers'
    | '/finance/payment-vouchers'
    | '/finance/reconciliation'
    | '/finance/reports'
    | '/hr/leave'
    | '/hr/payroll'
    | '/hr/salary'
    | '/hr/staff'
    | '/products/catalog'
    | '/products/expenses'
    | '/products/purchase-orders'
    | '/products/self-service'
    | '/sales/customer-statement'
    | '/sales/inter-branch'
    | '/sales/receipts'
    | '/sales/reports'
    | '/stakeholders/customers'
    | '/stakeholders/suppliers'
    | '/store/stock'
    | '/store/stores'
    | '/store/transfers'
    | '/sales/invoices/new'
    | '/sales/invoices/proforma'
    | '/sales/invoices'
  id:
    | '__root__'
    | '/_app'
    | '/_app/pos'
    | '/_app/'
    | '/_app/admin/settings'
    | '/_app/admin/users'
    | '/_app/finance/bank-cash'
    | '/_app/finance/chart-of-accounts'
    | '/_app/finance/ledgers'
    | '/_app/finance/payment-vouchers'
    | '/_app/finance/reconciliation'
    | '/_app/finance/reports'
    | '/_app/hr/leave'
    | '/_app/hr/payroll'
    | '/_app/hr/salary'
    | '/_app/hr/staff'
    | '/_app/products/catalog'
    | '/_app/products/expenses'
    | '/_app/products/purchase-orders'
    | '/_app/products/self-service'
    | '/_app/sales/customer-statement'
    | '/_app/sales/inter-branch'
    | '/_app/sales/invoices'
    | '/_app/sales/receipts'
    | '/_app/sales/reports'
    | '/_app/stakeholders/customers'
    | '/_app/stakeholders/suppliers'
    | '/_app/store/stock'
    | '/_app/store/stores'
    | '/_app/store/transfers'
    | '/_app/sales/invoices/new'
    | '/_app/sales/invoices/proforma'
    | '/_app/sales/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store/transfers': {
      id: '/_app/store/transfers'
      path: '/store/transfers'
      fullPath: '/store/transfers'
      preLoaderRoute: typeof AppStoreTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store/stores': {
      id: '/_app/store/stores'
      path: '/store/stores'
      fullPath: '/store/stores'
      preLoaderRoute: typeof AppStoreStoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store/stock': {
      id: '/_app/store/stock'
      path: '/store/stock'
      fullPath: '/store/stock'
      preLoaderRoute: typeof AppStoreStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stakeholders/suppliers': {
      id: '/_app/stakeholders/suppliers'
      path: '/stakeholders/suppliers'
      fullPath: '/stakeholders/suppliers'
      preLoaderRoute: typeof AppStakeholdersSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stakeholders/customers': {
      id: '/_app/stakeholders/customers'
      path: '/stakeholders/customers'
      fullPath: '/stakeholders/customers'
      preLoaderRoute: typeof AppStakeholdersCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/reports': {
      id: '/_app/sales/reports'
      path: '/sales/reports'
      fullPath: '/sales/reports'
      preLoaderRoute: typeof AppSalesReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/receipts': {
      id: '/_app/sales/receipts'
      path: '/sales/receipts'
      fullPath: '/sales/receipts'
      preLoaderRoute: typeof AppSalesReceiptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/invoices': {
      id: '/_app/sales/invoices'
      path: '/sales/invoices'
      fullPath: '/sales/invoices'
      preLoaderRoute: typeof AppSalesInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/inter-branch': {
      id: '/_app/sales/inter-branch'
      path: '/sales/inter-branch'
      fullPath: '/sales/inter-branch'
      preLoaderRoute: typeof AppSalesInterBranchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/customer-statement': {
      id: '/_app/sales/customer-statement'
      path: '/sales/customer-statement'
      fullPath: '/sales/customer-statement'
      preLoaderRoute: typeof AppSalesCustomerStatementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/self-service': {
      id: '/_app/products/self-service'
      path: '/products/self-service'
      fullPath: '/products/self-service'
      preLoaderRoute: typeof AppProductsSelfServiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/purchase-orders': {
      id: '/_app/products/purchase-orders'
      path: '/products/purchase-orders'
      fullPath: '/products/purchase-orders'
      preLoaderRoute: typeof AppProductsPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/expenses': {
      id: '/_app/products/expenses'
      path: '/products/expenses'
      fullPath: '/products/expenses'
      preLoaderRoute: typeof AppProductsExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/catalog': {
      id: '/_app/products/catalog'
      path: '/products/catalog'
      fullPath: '/products/catalog'
      preLoaderRoute: typeof AppProductsCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/staff': {
      id: '/_app/hr/staff'
      path: '/hr/staff'
      fullPath: '/hr/staff'
      preLoaderRoute: typeof AppHrStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/salary': {
      id: '/_app/hr/salary'
      path: '/hr/salary'
      fullPath: '/hr/salary'
      preLoaderRoute: typeof AppHrSalaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/payroll': {
      id: '/_app/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof AppHrPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/leave': {
      id: '/_app/hr/leave'
      path: '/hr/leave'
      fullPath: '/hr/leave'
      preLoaderRoute: typeof AppHrLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/reports': {
      id: '/_app/finance/reports'
      path: '/finance/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof AppFinanceReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/reconciliation': {
      id: '/_app/finance/reconciliation'
      path: '/finance/reconciliation'
      fullPath: '/finance/reconciliation'
      preLoaderRoute: typeof AppFinanceReconciliationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/payment-vouchers': {
      id: '/_app/finance/payment-vouchers'
      path: '/finance/payment-vouchers'
      fullPath: '/finance/payment-vouchers'
      preLoaderRoute: typeof AppFinancePaymentVouchersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/ledgers': {
      id: '/_app/finance/ledgers'
      path: '/finance/ledgers'
      fullPath: '/finance/ledgers'
      preLoaderRoute: typeof AppFinanceLedgersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/chart-of-accounts': {
      id: '/_app/finance/chart-of-accounts'
      path: '/finance/chart-of-accounts'
      fullPath: '/finance/chart-of-accounts'
      preLoaderRoute: typeof AppFinanceChartOfAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/bank-cash': {
      id: '/_app/finance/bank-cash'
      path: '/finance/bank-cash'
      fullPath: '/finance/bank-cash'
      preLoaderRoute: typeof AppFinanceBankCashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/invoices/': {
      id: '/_app/sales/invoices/'
      path: '/'
      fullPath: '/sales/invoices/'
      preLoaderRoute: typeof AppSalesInvoicesIndexRouteImport
      parentRoute: typeof AppSalesInvoicesRoute
    }
    '/_app/sales/invoices/proforma': {
      id: '/_app/sales/invoices/proforma'
      path: '/proforma'
      fullPath: '/sales/invoices/proforma'
      preLoaderRoute: typeof AppSalesInvoicesProformaRouteImport
      parentRoute: typeof AppSalesInvoicesRoute
    }
    '/_app/sales/invoices/new': {
      id: '/_app/sales/invoices/new'
      path: '/new'
      fullPath: '/sales/invoices/new'
      preLoaderRoute: typeof AppSalesInvoicesNewRouteImport
      parentRoute: typeof AppSalesInvoicesRoute
    }
  }
}

interface AppSalesInvoicesRouteChildren {
  AppSalesInvoicesNewRoute: typeof AppSalesInvoicesNewRoute
  AppSalesInvoicesProformaRoute: typeof AppSalesInvoicesProformaRoute
  AppSalesInvoicesIndexRoute: typeof AppSalesInvoicesIndexRoute
}

const AppSalesInvoicesRouteChildren: AppSalesInvoicesRouteChildren = {
  AppSalesInvoicesNewRoute: AppSalesInvoicesNewRoute,
  AppSalesInvoicesProformaRoute: AppSalesInvoicesProformaRoute,
  AppSalesInvoicesIndexRoute: AppSalesInvoicesIndexRoute,
}

const AppSalesInvoicesRouteWithChildren =
  AppSalesInvoicesRoute._addFileChildren(AppSalesInvoicesRouteChildren)

interface AppRouteChildren {
  AppPosRoute: typeof AppPosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppFinanceBankCashRoute: typeof AppFinanceBankCashRoute
  AppFinanceChartOfAccountsRoute: typeof AppFinanceChartOfAccountsRoute
  AppFinanceLedgersRoute: typeof AppFinanceLedgersRoute
  AppFinancePaymentVouchersRoute: typeof AppFinancePaymentVouchersRoute
  AppFinanceReconciliationRoute: typeof AppFinanceReconciliationRoute
  AppFinanceReportsRoute: typeof AppFinanceReportsRoute
  AppHrLeaveRoute: typeof AppHrLeaveRoute
  AppHrPayrollRoute: typeof AppHrPayrollRoute
  AppHrSalaryRoute: typeof AppHrSalaryRoute
  AppHrStaffRoute: typeof AppHrStaffRoute
  AppProductsCatalogRoute: typeof AppProductsCatalogRoute
  AppProductsExpensesRoute: typeof AppProductsExpensesRoute
  AppProductsPurchaseOrdersRoute: typeof AppProductsPurchaseOrdersRoute
  AppProductsSelfServiceRoute: typeof AppProductsSelfServiceRoute
  AppSalesCustomerStatementRoute: typeof AppSalesCustomerStatementRoute
  AppSalesInterBranchRoute: typeof AppSalesInterBranchRoute
  AppSalesInvoicesRoute: typeof AppSalesInvoicesRouteWithChildren
  AppSalesReceiptsRoute: typeof AppSalesReceiptsRoute
  AppSalesReportsRoute: typeof AppSalesReportsRoute
  AppStakeholdersCustomersRoute: typeof AppStakeholdersCustomersRoute
  AppStakeholdersSuppliersRoute: typeof AppStakeholdersSuppliersRoute
  AppStoreStockRoute: typeof AppStoreStockRoute
  AppStoreStoresRoute: typeof AppStoreStoresRoute
  AppStoreTransfersRoute: typeof AppStoreTransfersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPosRoute: AppPosRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppFinanceBankCashRoute: AppFinanceBankCashRoute,
  AppFinanceChartOfAccountsRoute: AppFinanceChartOfAccountsRoute,
  AppFinanceLedgersRoute: AppFinanceLedgersRoute,
  AppFinancePaymentVouchersRoute: AppFinancePaymentVouchersRoute,
  AppFinanceReconciliationRoute: AppFinanceReconciliationRoute,
  AppFinanceReportsRoute: AppFinanceReportsRoute,
  AppHrLeaveRoute: AppHrLeaveRoute,
  AppHrPayrollRoute: AppHrPayrollRoute,
  AppHrSalaryRoute: AppHrSalaryRoute,
  AppHrStaffRoute: AppHrStaffRoute,
  AppProductsCatalogRoute: AppProductsCatalogRoute,
  AppProductsExpensesRoute: AppProductsExpensesRoute,
  AppProductsPurchaseOrdersRoute: AppProductsPurchaseOrdersRoute,
  AppProductsSelfServiceRoute: AppProductsSelfServiceRoute,
  AppSalesCustomerStatementRoute: AppSalesCustomerStatementRoute,
  AppSalesInterBranchRoute: AppSalesInterBranchRoute,
  AppSalesInvoicesRoute: AppSalesInvoicesRouteWithChildren,
  AppSalesReceiptsRoute: AppSalesReceiptsRoute,
  AppSalesReportsRoute: AppSalesReportsRoute,
  AppStakeholdersCustomersRoute: AppStakeholdersCustomersRoute,
  AppStakeholdersSuppliersRoute: AppStakeholdersSuppliersRoute,
  AppStoreStockRoute: AppStoreStockRoute,
  AppStoreStoresRoute: AppStoreStoresRoute,
  AppStoreTransfersRoute: AppStoreTransfersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
